<?php
if (!defined('ABSPATH')) { exit; }
$lang = cia_home_language();
$copy = $lang === 'en' ? array(
 'event'=>'Event','when'=>'Date and time','where'=>'Venue','format'=>'Format','speakers'=>'Speakers','speaker_role'=>'Speaker','speaker_fallback'=>'Speaker portrait is not yet available.','support'=>'Collaborators at this event','support_intro'=>'Organizations recorded in this event taxonomy. A listing identifies event participation; it does not imply an active relationship beyond this record.','register'=>'Register','open'=>'Registration open','scheduled'=>'Registration opens soon','closed'=>'Event ended','unavailable'=>'Registration unavailable','map'=>'Open map','stream'=>'Open public stream','about'=>'About this event','back'=>'Browse all events','unverified'=>'To be confirmed','logo_fallback'=>'A verified local logo is not available; a neutral monogram is shown.','sponsor'=>'Sponsor','community'=>'Community supporter','education'=>'Education partner','agenda'=>'Agenda','agenda_intro'=>'Sessions are grouped by event day and shown in local Jakarta time.','day'=>'Day','moderator'=>'Moderator','session_speakers'=>'Speakers','room'=>'Room','sessions'=>'sessions','opportunities'=>'Open calls','opportunities_intro'=>'Speaker, sponsor, and volunteer opportunities connected to this conference. Only published calls are shown.','call_proposal'=>'Call for Proposal','call_sponsor'=>'Call for Sponsor','call_volunteer'=>'Call for Volunteer','call_planned'=>'Details being prepared','call_scheduled'=>'Scheduled','call_open'=>'Open','call_closed'=>'Closed','call_deadline'=>'Closes','view_call'=>'View details'
) : array(
 'event'=>'Event','when'=>'Tanggal dan waktu','where'=>'Lokasi','format'=>'Format','speakers'=>'Pembicara','speaker_role'=>'Pembicara','speaker_fallback'=>'Foto pembicara belum tersedia.','support'=>'Kolaborator event ini','support_intro'=>'Organisasi yang tercatat dalam taxonomy event ini. Listing menunjukkan keterlibatan pada event, bukan klaim hubungan aktif di luar rekam tersebut.','register'=>'Daftar event','open'=>'Registrasi dibuka','scheduled'=>'Registrasi segera dibuka','closed'=>'Event telah selesai','unavailable'=>'Registrasi tidak tersedia','map'=>'Buka peta','stream'=>'Buka siaran publik','about'=>'Tentang event ini','back'=>'Jelajahi semua event','unverified'=>'Belum dikonfirmasi','logo_fallback'=>'Logo lokal terverifikasi belum tersedia; sebagai gantinya ditampilkan monogram netral.','sponsor'=>'Sponsor','community'=>'Pendukung komunitas','education'=>'Mitra pendidikan','agenda'=>'Agenda','agenda_intro'=>'Sesi dikelompokkan per hari event dan ditampilkan dalam waktu Jakarta.','day'=>'Hari','moderator'=>'Moderator','session_speakers'=>'Pembicara','room'=>'Ruang','sessions'=>'sesi','opportunities'=>'Call terbuka','opportunities_intro'=>'Kesempatan pembicara, sponsor, dan volunteer yang terhubung ke conference ini. Hanya call yang sudah dipublikasikan yang ditampilkan.','call_proposal'=>'Call for Proposal','call_sponsor'=>'Call for Sponsor','call_volunteer'=>'Call for Volunteer','call_planned'=>'Detail sedang disiapkan','call_scheduled'=>'Terjadwal','call_open'=>'Dibuka','call_closed'=>'Ditutup','call_deadline'=>'Ditutup','view_call'=>'Lihat detail'
);
$taxonomy_roles = array('sponsors'=>$copy['sponsor'],'community_support'=>$copy['community'],'education-partner'=>$copy['education']);
$dark_logos = array('amd','kementrian-komunikasi-dan-digital','sekolah-vokasi-universitas-gajah-mada','sivali-cloud-technology');
$display_names = array('kementrian-komunikasi-dan-digital'=>'Kementerian Komunikasi dan Digital');
get_header();
while (have_posts()): the_post();
$id=get_the_ID();
$start=cia_event_datetime($id,'event_start'); $end=cia_event_datetime($id,'event_end');
$venue=trim((string)get_post_meta($id,'venue',true));
$registration_link=cia_event_safe_url(get_post_meta($id,'registration_link',true));
$webinar_link=cia_event_safe_url(get_post_meta($id,'webinar_link',true));
$google_map_link=cia_event_safe_url(get_post_meta($id,'google_map_link',true));
$public_webinar=get_post_meta($id,'_cia_public_webinar_link',true)==='1' ? $webinar_link : '';
$state=cia_event_registration_state($id);
$types=get_the_terms($id,'event_type'); $speakers=get_the_terms($id,'speakers');
$support=array(); foreach($taxonomy_roles as $taxonomy=>$role){ $items=get_the_terms($id,$taxonomy); if($items && !is_wp_error($items)){ foreach($items as $item){ $support[] = array('term'=>$item,'taxonomy'=>$taxonomy,'role'=>$role); } } }
$sessions=function_exists('cia_get_event_sessions') ? cia_get_event_sessions($id) : array();
$session_count=count($sessions); $agenda_days=array();
foreach($sessions as $session){$day=max(1,(int)get_post_meta($session->ID,'_cia_session_day',true));if(!isset($agenda_days[$day])){$agenda_days[$day]=array();}$agenda_days[$day][]=$session;}
$event_calls=function_exists('cia_get_event_calls') ? cia_get_event_calls($id) : array();
?>
<article class="event-inspect">
  <header class="event-inspect-hero"><div class="container">
    <a class="event-back-link" href="<?php echo esc_url(cia_archive_link('events','/events/')); ?>">← <?php echo esc_html($copy['back']); ?></a>
    <div class="event-inspect-heading"><div><span class="media-kicker section-brow"><?php echo esc_html($copy['event']); ?><?php if($types && !is_wp_error($types)): ?> · <?php echo esc_html(implode(' · ',wp_list_pluck($types,'name'))); endif; ?></span><h1><?php the_title(); ?></h1></div><span class="event-state event-state-<?php echo esc_attr($state); ?>"><?php echo esc_html($copy[$state]); ?></span></div>
  </div></header>
  <section class="event-inspect-main"><div class="container event-inspect-grid">
    <div class="event-inspect-content">
      <div class="event-inspect-poster"><?php cia_event_media_gallery($id,'full'); ?></div>
      <div class="event-inspect-copy"><span class="media-kicker section-brow"><?php echo esc_html($copy['about']); ?></span><div class="entry-content"><?php the_content(); ?></div></div>
      <?php if($session_count): ?><section id="agenda" class="event-agenda" aria-labelledby="event-agenda-title"><header class="event-people-heading"><span class="media-kicker section-brow"><?php echo esc_html(sprintf('%02d',$session_count)); ?></span><div><h2 id="event-agenda-title"><?php echo esc_html($copy['agenda']); ?></h2><p><?php echo esc_html($copy['agenda_intro']); ?></p></div></header>
        <?php foreach($agenda_days as $day=>$day_sessions): $first_start=(string)get_post_meta($day_sessions[0]->ID,'_cia_session_start',true); $day_date=DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$first_start,cia_event_timezone()); $month_id=array(1=>'Jan',2=>'Feb',3=>'Mar',4=>'Apr',5=>'Mei',6=>'Jun',7=>'Jul',8=>'Agu',9=>'Sep',10=>'Okt',11=>'Nov',12=>'Des'); $date_label=$day_date ? ($lang==='en' ? $day_date->format('j M Y') : $day_date->format('j').' '.$month_id[(int)$day_date->format('n')].' '.$day_date->format('Y')) : ''; ?>
        <section class="event-agenda-day" aria-labelledby="event-agenda-day-<?php echo esc_attr((string)$day); ?>"><header><p><?php echo esc_html($copy['day'].' '.$day); ?></p><h3 id="event-agenda-day-<?php echo esc_attr((string)$day); ?>"><?php echo esc_html($date_label); ?></h3></header><ol>
          <?php foreach($day_sessions as $session): $session_start=(string)get_post_meta($session->ID,'_cia_session_start',true); $session_end=(string)get_post_meta($session->ID,'_cia_session_end',true); $room=(string)get_post_meta($session->ID,'_cia_session_room',true); $moderator=(string)get_post_meta($session->ID,'_cia_session_moderator',true); $session_type=(string)get_post_meta($session->ID,'_cia_session_type',true); $speaker_text=(string)get_post_meta($session->ID,'_cia_session_speakers_text',true); $session_speakers=array_values(array_filter(array_map('trim',preg_split('/\R/',$speaker_text)))); $plain=trim(wp_strip_all_tags(strip_shortcodes($session->post_content))); $session_title=get_the_title($session); if(str_starts_with($plain,$session_title)){$plain=trim(substr($plain,strlen($session_title)));} $description=trim((string)preg_split('/\s+Moderator:\s*/i',$plain,2)[0]); ?>
          <li id="session-<?php echo esc_attr((string)$session->ID); ?>" class="event-session-item" data-event-session="<?php echo esc_attr((string)$session->ID); ?>"><details><summary class="event-session-summary"><time datetime="<?php echo esc_attr(str_replace(' ','T',$session_start)); ?>"><strong><?php echo esc_html(substr($session_start,11,5)); ?></strong><span>–<?php echo esc_html(substr($session_end,11,5)); ?> WIB</span></time><span><small><?php echo esc_html($session_type); ?></small><strong><?php echo esc_html($session_title); ?></strong><?php if($room): ?><em><?php echo esc_html($room); ?></em><?php endif; ?></span><b aria-hidden="true">+</b></summary><div class="event-session-detail"><?php if($description): ?><p><?php echo esc_html(wp_trim_words($description,70)); ?></p><?php endif; ?><dl class="event-session-people"><?php if($moderator): ?><div><dt><?php echo esc_html($copy['moderator']); ?></dt><dd><?php echo esc_html($moderator); ?></dd></div><?php endif; ?><?php if($session_speakers): ?><div class="event-session-speakers"><dt><?php echo esc_html($copy['session_speakers']); ?></dt><dd><?php echo esc_html(implode(' · ',$session_speakers)); ?></dd></div><?php endif; ?><?php if($room): ?><div><dt><?php echo esc_html($copy['room']); ?></dt><dd><?php echo esc_html($room); ?></dd></div><?php endif; ?></dl></div></details></li>
          <?php endforeach; ?></ol></section><?php endforeach; ?>
      </section><?php endif; ?>
      <?php if($event_calls): ?><section id="event-opportunities" class="event-opportunities" aria-labelledby="event-opportunities-title"><header class="event-people-heading"><span class="media-kicker section-brow"><?php echo esc_html(sprintf('%02d',count($event_calls))); ?></span><div><h2 id="event-opportunities-title"><?php echo esc_html($copy['opportunities']); ?></h2><p><?php echo esc_html($copy['opportunities_intro']); ?></p></div></header><ol class="event-call-list">
        <?php foreach($event_calls as $call): $call_type=(string)get_post_meta($call->ID,'_cia_call_type',true); if(!in_array($call_type,array('proposal','sponsor','volunteer'),true)){$call_type='proposal';} $call_state=cia_event_call_state($call->ID); $call_title=cia_event_call_localized($call->ID,'title',$lang); $call_summary=cia_event_call_localized($call->ID,'summary',$lang); $call_close=(string)get_post_meta($call->ID,'_cia_call_close',true); $call_close_date=$call_close ? DateTimeImmutable::createFromFormat('!Y-m-d H:i:s',$call_close,cia_event_timezone()) : false; $call_url=cia_localized_url(get_permalink($call),$lang); ?>
        <li class="event-call-item"><div><p class="event-call-type"><?php echo esc_html($copy['call_'.$call_type]); ?></p><h3><a href="<?php echo esc_url($call_url); ?>"><?php echo esc_html($call_title); ?></a></h3><?php if($call_summary): ?><p><?php echo esc_html($call_summary); ?></p><?php endif; ?></div><div class="event-call-action"><span class="event-call-state event-call-state-<?php echo esc_attr($call_state); ?>"><?php echo esc_html($copy['call_'.$call_state]); ?></span><?php if($call_close_date): ?><small><?php echo esc_html($copy['call_deadline'].' '.$call_close_date->format('d M Y · H:i').' WIB'); ?></small><?php endif; ?><a class="event-call-link" href="<?php echo esc_url($call_url); ?>"><?php echo esc_html($copy['view_call']); ?> →</a></div></li>
        <?php endforeach; ?></ol></section><?php endif; ?>
      <?php if($speakers && !is_wp_error($speakers)): ?><section class="event-people event-speakers" aria-labelledby="event-speakers-title"><header class="event-people-heading"><span class="media-kicker section-brow"><?php echo esc_html(sprintf('%02d',count($speakers))); ?></span><h2 id="event-speakers-title"><?php echo esc_html($copy['speakers']); ?></h2></header><div class="event-speaker-grid"><?php foreach($speakers as $speaker):
        $person=cia_people_directory_record($speaker->term_id); $portrait='';
        $candidate=(string)($person['portrait']['theme_path'] ?? '');
        if(preg_match('~^assets/people/[a-zA-Z0-9._-]+\.png$~',$candidate) && is_file(get_template_directory().'/'.$candidate)){ $portrait=$candidate; }
        $speaker_link=get_term_link($speaker); $speaker_link=is_wp_error($speaker_link) ? '#' : $speaker_link;
        $initials=cia_entity_initials($speaker->name);
      ?><article class="event-speaker-card"><a class="event-speaker-portrait" href="<?php echo esc_url($speaker_link); ?>"><?php if($portrait): ?><img src="<?php echo esc_url(get_template_directory_uri().'/'.$portrait); ?>" alt="" width="400" height="400" loading="lazy" decoding="async"><?php else: ?><span aria-hidden="true"><?php echo esc_html($initials); ?></span><span class="screen-reader-text"><?php echo esc_html($copy['speaker_fallback']); ?></span><?php endif; ?></a><div><p><?php echo esc_html($copy['speaker_role']); ?></p><h3><a href="<?php echo esc_url($speaker_link); ?>"><?php echo esc_html($speaker->name); ?></a></h3><?php if(!empty($person['affiliation_note'])): ?><small><?php echo esc_html($person['affiliation_note']); ?></small><?php endif; ?></div></article><?php endforeach; ?></div></section><?php endif; ?>
      <?php if($support): ?><section class="event-people event-collaborators" aria-labelledby="event-collaborators-title"><header class="event-people-heading"><span class="media-kicker section-brow"><?php echo esc_html(sprintf('%02d',count($support))); ?></span><div><h2 id="event-collaborators-title"><?php echo esc_html($copy['support']); ?></h2><p><?php echo esc_html($copy['support_intro']); ?></p></div></header><div class="event-collaborator-grid"><?php foreach($support as $entry): $item=$entry['term']; $display_name=$display_names[$item->slug] ?? $item->name; $logo=cia_partner_logo_record($item->slug); $logo_file=(string)($logo['file'] ?? ''); $event_url=add_query_arg('event_collaborator',$entry['taxonomy'].':'.$item->slug,cia_localized_url(get_post_type_archive_link('events'),$lang)); ?><a class="event-collaborator-card" href="<?php echo esc_url($event_url); ?>"><span class="event-collaborator-logo <?php echo in_array($item->slug,$dark_logos,true)?'is-dark':''; ?>"><?php if($logo_file): ?><img src="<?php echo esc_url(get_template_directory_uri().'/assets/partner-logos/'.$logo_file); ?>" alt="<?php echo esc_attr($display_name.' logo'); ?>" loading="lazy" decoding="async"><?php else: ?><span aria-hidden="true"><?php echo esc_html(cia_entity_initials($display_name)); ?></span><span class="screen-reader-text"><?php echo esc_html($copy['logo_fallback']); ?></span><?php endif; ?></span><span><small><?php echo esc_html($entry['role']); ?></small><strong><?php echo esc_html($display_name); ?></strong></span></a><?php endforeach; ?></div></section><?php endif; ?>
    </div>
    <aside class="event-detail-panel" aria-label="Event details"><div class="event-sidebar-inner">
      <dl>
        <div><dt><?php echo esc_html($copy['when']); ?></dt><dd><?php echo esc_html(cia_event_format_range($id,$lang) ?: $copy['unverified']); ?></dd></div>
        <div><dt><?php echo esc_html($copy['where']); ?></dt><dd><?php echo esc_html($venue ?: $copy['unverified']); ?><?php if($google_map_link): ?><a href="<?php echo esc_url($google_map_link); ?>" rel="external noopener"><?php echo esc_html($copy['map']); ?> ↗</a><?php endif; ?></dd></div>
        <div><dt><?php echo esc_html($copy['format']); ?></dt><dd><?php echo ($types && !is_wp_error($types)) ? esc_html(implode(', ',wp_list_pluck($types,'name'))) : esc_html($copy['unverified']); ?></dd></div>
      </dl>
      <?php if($state==='open' && $registration_link): ?><a class="event-register-button" href="<?php echo esc_url($registration_link); ?>" rel="external noopener"><?php echo esc_html($copy['register']); ?> ↗</a><?php else: ?><div class="event-registration-note"><?php echo esc_html($copy[$state]); ?></div><?php endif; ?>
      <?php if($public_webinar): ?><a class="event-stream-link" href="<?php echo esc_url($public_webinar); ?>" rel="external noopener"><?php echo esc_html($copy['stream']); ?> ↗</a><?php endif; ?>
    </div></aside>
  </div></section>
</article>
<?php endwhile; get_footer(); ?>
